# Generated by Django 5.2.8 on 2025-11-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproducto',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
