# Generated by Django 5.2.8 on 2025-12-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_detalleproducto_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproducto',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
